baseURL = 'https://alexisnowicki.com'
languageCode = 'en-us'
title = 'Alexis Nowicki'
theme = "paper"
font = "TimesNewRoman"

[menu]
  [[menu.nav]]
    name = "book publicity"
    url = "/publicity/"
    weight = 1