baseURL = 'https://gentle-daffodil-2.netlify.app'
languageCode = 'en-us'
title = 'Alexis Nowicki'
theme = "paper"
font = "TimesDotRoman"

[menu]
  [[menu.nav]]
    name = "book publicity"
    url = "/publicity/"
    weight = 1